services:
  db:
    image: postgres:15
    container_name: job_search_db
    environment:
      POSTGRES_USER: tural_user
      POSTGRES_PASSWORD: tural_pass
      POSTGRES_DB: job_search_api_db
    ports:
      - "5433:5432"
    networks:
      - job-network

  app:
    build: .
    container_name: job_search_app
    ports:
      - "8019:8019"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/job_search_api_db
      SPRING_DATASOURCE_USERNAME: tural_user
      SPRING_DATASOURCE_PASSWORD: tural_pass
    networks:
      - job-network

networks:
  job-network:
    driver: bridge